from pathlib import Path

path = Path('lib/app.dart')
text = path.read_text()
old = """    return MaterialApp(\n      title: 'Arus Finance',\n      debugShowCheckedModeBanner: false,\n      theme: AppTheme.light(_themePreferences.themeId),\n      darkTheme: AppTheme.dark(_themePreferences.themeId),\n      themeMode: _themePreferences.themeMode,\n      home: _buildPrivacyProtectedHome(),\n    );\n  }\n\n  Widget _buildPrivacyProtectedHome() {\n    return Stack(\n      fit: StackFit.expand,\n      children: [\n        _buildHome(),\n        if (_privacyShielded)\n          ColoredBox(\n            color: Color(0xFF101114),\n            child: Semantics(\n              container: true,\n              label: 'Arus disembunyikan saat aplikasi tidak aktif',\n              child: Center(\n                child: Icon(Icons.lock_outline, color: Colors.white70, size: 36),\n              ),\n            ),\n          ),\n      ],\n    );\n  }\n\n  Widget _buildHome() {\n"""
new = """    return MaterialApp(\n      title: 'Arus Finance',\n      debugShowCheckedModeBanner: false,\n      theme: AppTheme.light(_themePreferences.themeId),\n      darkTheme: AppTheme.dark(_themePreferences.themeId),\n      themeMode: _themePreferences.themeMode,\n      // Security must wrap the Navigator itself, not only the home route.\n      // Otherwise dialogs/bottom sheets pushed above `home` can remain\n      // interactive while LockGate has already locked the page underneath.\n      builder: (context, child) => _buildSecurityEnvelope(child),\n      home: _buildHome(),\n    );\n  }\n\n  Widget _buildSecurityEnvelope(Widget? routedChild) {\n    return Stack(\n      fit: StackFit.expand,\n      children: [\n        LockGate(\n          security: widget.security,\n          child: routedChild ?? const SizedBox.shrink(),\n        ),\n        if (_privacyShielded)\n          const ColoredBox(\n            color: Color(0xFF101114),\n            child: Semantics(\n              container: true,\n              label: 'Arus disembunyikan saat aplikasi tidak aktif',\n              child: Center(\n                child: Icon(Icons.lock_outline, color: Colors.white70, size: 36),\n              ),\n            ),\n          ),\n      ],\n    );\n  }\n\n  Widget _buildHome() {\n"""
if old not in text:
    raise SystemExit('target block not found')
text = text.replace(old, new)
text = text.replace("""      return LockGate(\n        security: widget.security,\n        child: RecoveryScreen(\n          controller: widget.controller,\n          database: widget.database,\n          errorMessage: widget.controller.errorMessage!,\n        ),\n      );\n""", """      return RecoveryScreen(\n        controller: widget.controller,\n        database: widget.database,\n        errorMessage: widget.controller.errorMessage!,\n      );\n""")
text = text.replace("""    return LockGate(\n      security: widget.security,\n      child: AppShell(controller: widget.controller, database: widget.database, security: widget.security),\n    );\n""", """    return AppShell(\n      controller: widget.controller,\n      database: widget.database,\n      security: widget.security,\n    );\n""")
path.write_text(text)
